# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9ad989a69b504a89af23ba459fd2a3ef355e114bb3daa251151575aee40472e71a3a03b2685b61b0d10fbd938b26a0126aa2ec3a826491429020d212f4f6fe41

test:
  secret_key_base: f87742194f6fb73929aeee695314a6d5d3b6108e5b333e5900f092d327f0a27804d83cbb66b453cb81b07b69ae79373ab6ba18c10c2941870f645138f0115306

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f87742194f6fb73929aeee695314a6d5d3b6108e5b333e5900f092d327f0a27804d83cbb66b453cb81b07b69ae79373ab6ba18c10c2941870f645138f0115307
